// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthenticateRequest.ptoto

package com.zsxg.im.protocol;

public final class AuthenticateRequestProto {
    private AuthenticateRequestProto() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface AuthenticateRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:im.AuthenticateRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string uid = 1;</code>
         * @return Whether the uid field is set.
         */
        boolean hasUid();
        /**
         * <code>required string uid = 1;</code>
         * @return The uid.
         */
        java.lang.String getUid();
        /**
         * <code>required string uid = 1;</code>
         * @return The bytes for uid.
         */
        com.google.protobuf.ByteString
        getUidBytes();

        /**
         * <code>required string token = 2;</code>
         * @return Whether the token field is set.
         */
        boolean hasToken();
        /**
         * <code>required string token = 2;</code>
         * @return The token.
         */
        java.lang.String getToken();
        /**
         * <code>required string token = 2;</code>
         * @return The bytes for token.
         */
        com.google.protobuf.ByteString
        getTokenBytes();

        /**
         * <code>required int64 timestamp = 3;</code>
         * @return Whether the timestamp field is set.
         */
        boolean hasTimestamp();
        /**
         * <code>required int64 timestamp = 3;</code>
         * @return The timestamp.
         */
        long getTimestamp();
    }
    /**
     * Protobuf type {@code im.AuthenticateRequest}
     */
    public static final class AuthenticateRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:im.AuthenticateRequest)
            AuthenticateRequestOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use AuthenticateRequest.newBuilder() to construct.
        private AuthenticateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private AuthenticateRequest() {
            uid_ = "";
            token_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new AuthenticateRequest();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private AuthenticateRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            uid_ = bs;
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            token_ = bs;
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            timestamp_ = input.readInt64();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.zsxg.im.protocol.AuthenticateRequestProto.internal_static_im_AuthenticateRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.zsxg.im.protocol.AuthenticateRequestProto.internal_static_im_AuthenticateRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest.class, com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest.Builder.class);
        }

        private int bitField0_;
        public static final int UID_FIELD_NUMBER = 1;
        private volatile java.lang.Object uid_;
        /**
         * <code>required string uid = 1;</code>
         * @return Whether the uid field is set.
         */
        @java.lang.Override
        public boolean hasUid() {
            return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required string uid = 1;</code>
         * @return The uid.
         */
        @java.lang.Override
        public java.lang.String getUid() {
            java.lang.Object ref = uid_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    uid_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string uid = 1;</code>
         * @return The bytes for uid.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getUidBytes() {
            java.lang.Object ref = uid_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                uid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TOKEN_FIELD_NUMBER = 2;
        private volatile java.lang.Object token_;
        /**
         * <code>required string token = 2;</code>
         * @return Whether the token field is set.
         */
        @java.lang.Override
        public boolean hasToken() {
            return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>required string token = 2;</code>
         * @return The token.
         */
        @java.lang.Override
        public java.lang.String getToken() {
            java.lang.Object ref = token_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    token_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string token = 2;</code>
         * @return The bytes for token.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getTokenBytes() {
            java.lang.Object ref = token_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                token_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TIMESTAMP_FIELD_NUMBER = 3;
        private long timestamp_;
        /**
         * <code>required int64 timestamp = 3;</code>
         * @return Whether the timestamp field is set.
         */
        @java.lang.Override
        public boolean hasTimestamp() {
            return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>required int64 timestamp = 3;</code>
         * @return The timestamp.
         */
        @java.lang.Override
        public long getTimestamp() {
            return timestamp_;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasUid()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasToken()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasTimestamp()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                output.writeInt64(3, timestamp_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(3, timestamp_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest)) {
                return super.equals(obj);
            }
            com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest other = (com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest) obj;

            if (hasUid() != other.hasUid()) return false;
            if (hasUid()) {
                if (!getUid()
                        .equals(other.getUid())) return false;
            }
            if (hasToken() != other.hasToken()) return false;
            if (hasToken()) {
                if (!getToken()
                        .equals(other.getToken())) return false;
            }
            if (hasTimestamp() != other.hasTimestamp()) return false;
            if (hasTimestamp()) {
                if (getTimestamp()
                        != other.getTimestamp()) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasUid()) {
                hash = (37 * hash) + UID_FIELD_NUMBER;
                hash = (53 * hash) + getUid().hashCode();
            }
            if (hasToken()) {
                hash = (37 * hash) + TOKEN_FIELD_NUMBER;
                hash = (53 * hash) + getToken().hashCode();
            }
            if (hasTimestamp()) {
                hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getTimestamp());
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code im.AuthenticateRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:im.AuthenticateRequest)
                com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.zsxg.im.protocol.AuthenticateRequestProto.internal_static_im_AuthenticateRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.zsxg.im.protocol.AuthenticateRequestProto.internal_static_im_AuthenticateRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest.class, com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest.Builder.class);
            }

            // Construct using com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                uid_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                token_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                timestamp_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.zsxg.im.protocol.AuthenticateRequestProto.internal_static_im_AuthenticateRequest_descriptor;
            }

            @java.lang.Override
            public com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest getDefaultInstanceForType() {
                return com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest.getDefaultInstance();
            }

            @java.lang.Override
            public com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest build() {
                com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest buildPartial() {
                com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest result = new com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.uid_ = uid_;
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.token_ = token_;
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.timestamp_ = timestamp_;
                    to_bitField0_ |= 0x00000004;
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest) {
                    return mergeFrom((com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest other) {
                if (other == com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest.getDefaultInstance()) return this;
                if (other.hasUid()) {
                    bitField0_ |= 0x00000001;
                    uid_ = other.uid_;
                    onChanged();
                }
                if (other.hasToken()) {
                    bitField0_ |= 0x00000002;
                    token_ = other.token_;
                    onChanged();
                }
                if (other.hasTimestamp()) {
                    setTimestamp(other.getTimestamp());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasUid()) {
                    return false;
                }
                if (!hasToken()) {
                    return false;
                }
                if (!hasTimestamp()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.lang.Object uid_ = "";
            /**
             * <code>required string uid = 1;</code>
             * @return Whether the uid field is set.
             */
            public boolean hasUid() {
                return ((bitField0_ & 0x00000001) != 0);
            }
            /**
             * <code>required string uid = 1;</code>
             * @return The uid.
             */
            public java.lang.String getUid() {
                java.lang.Object ref = uid_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        uid_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string uid = 1;</code>
             * @return The bytes for uid.
             */
            public com.google.protobuf.ByteString
            getUidBytes() {
                java.lang.Object ref = uid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    uid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string uid = 1;</code>
             * @param value The uid to set.
             * @return This builder for chaining.
             */
            public Builder setUid(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                uid_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string uid = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearUid() {
                bitField0_ = (bitField0_ & ~0x00000001);
                uid_ = getDefaultInstance().getUid();
                onChanged();
                return this;
            }
            /**
             * <code>required string uid = 1;</code>
             * @param value The bytes for uid to set.
             * @return This builder for chaining.
             */
            public Builder setUidBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                uid_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object token_ = "";
            /**
             * <code>required string token = 2;</code>
             * @return Whether the token field is set.
             */
            public boolean hasToken() {
                return ((bitField0_ & 0x00000002) != 0);
            }
            /**
             * <code>required string token = 2;</code>
             * @return The token.
             */
            public java.lang.String getToken() {
                java.lang.Object ref = token_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        token_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string token = 2;</code>
             * @return The bytes for token.
             */
            public com.google.protobuf.ByteString
            getTokenBytes() {
                java.lang.Object ref = token_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    token_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string token = 2;</code>
             * @param value The token to set.
             * @return This builder for chaining.
             */
            public Builder setToken(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                token_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string token = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearToken() {
                bitField0_ = (bitField0_ & ~0x00000002);
                token_ = getDefaultInstance().getToken();
                onChanged();
                return this;
            }
            /**
             * <code>required string token = 2;</code>
             * @param value The bytes for token to set.
             * @return This builder for chaining.
             */
            public Builder setTokenBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                token_ = value;
                onChanged();
                return this;
            }

            private long timestamp_ ;
            /**
             * <code>required int64 timestamp = 3;</code>
             * @return Whether the timestamp field is set.
             */
            @java.lang.Override
            public boolean hasTimestamp() {
                return ((bitField0_ & 0x00000004) != 0);
            }
            /**
             * <code>required int64 timestamp = 3;</code>
             * @return The timestamp.
             */
            @java.lang.Override
            public long getTimestamp() {
                return timestamp_;
            }
            /**
             * <code>required int64 timestamp = 3;</code>
             * @param value The timestamp to set.
             * @return This builder for chaining.
             */
            public Builder setTimestamp(long value) {
                bitField0_ |= 0x00000004;
                timestamp_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required int64 timestamp = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearTimestamp() {
                bitField0_ = (bitField0_ & ~0x00000004);
                timestamp_ = 0L;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:im.AuthenticateRequest)
        }

        // @@protoc_insertion_point(class_scope:im.AuthenticateRequest)
        private static final com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest();
        }

        public static com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated public static final com.google.protobuf.Parser<AuthenticateRequest>
                PARSER = new com.google.protobuf.AbstractParser<AuthenticateRequest>() {
            @java.lang.Override
            public AuthenticateRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new AuthenticateRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<AuthenticateRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<AuthenticateRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.zsxg.im.protocol.AuthenticateRequestProto.AuthenticateRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_im_AuthenticateRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_im_AuthenticateRequest_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\031AuthenticateRequest.ptoto\022\002im\"D\n\023Authe" +
                        "nticateRequest\022\013\n\003uid\030\001 \002(\t\022\r\n\005token\030\002 \002" +
                        "(\t\022\021\n\ttimestamp\030\003 \002(\003B0\n\024com.zsxg.im.pro" +
                        "tocolB\030AuthenticateRequestProto"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_im_AuthenticateRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_im_AuthenticateRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_im_AuthenticateRequest_descriptor,
                new java.lang.String[] { "Uid", "Token", "Timestamp", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
