// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthenticateResponse.ptoto

package com.zsxg.im.protocol;

public final class AuthenticateResponseProto {
    private AuthenticateResponseProto() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface AuthenticateResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:im.AuthenticateResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int32 status = 1;</code>
         * @return Whether the status field is set.
         */
        boolean hasStatus();
        /**
         * <code>required int32 status = 1;</code>
         * @return The status.
         */
        int getStatus();

        /**
         * <code>required int32 errorCode = 2;</code>
         * @return Whether the errorCode field is set.
         */
        boolean hasErrorCode();
        /**
         * <code>required int32 errorCode = 2;</code>
         * @return The errorCode.
         */
        int getErrorCode();

        /**
         * <code>required string errorMessage = 3;</code>
         * @return Whether the errorMessage field is set.
         */
        boolean hasErrorMessage();
        /**
         * <code>required string errorMessage = 3;</code>
         * @return The errorMessage.
         */
        java.lang.String getErrorMessage();
        /**
         * <code>required string errorMessage = 3;</code>
         * @return The bytes for errorMessage.
         */
        com.google.protobuf.ByteString
        getErrorMessageBytes();

        /**
         * <code>required string uid = 4;</code>
         * @return Whether the uid field is set.
         */
        boolean hasUid();
        /**
         * <code>required string uid = 4;</code>
         * @return The uid.
         */
        java.lang.String getUid();
        /**
         * <code>required string uid = 4;</code>
         * @return The bytes for uid.
         */
        com.google.protobuf.ByteString
        getUidBytes();

        /**
         * <code>required string token = 5;</code>
         * @return Whether the token field is set.
         */
        boolean hasToken();
        /**
         * <code>required string token = 5;</code>
         * @return The token.
         */
        java.lang.String getToken();
        /**
         * <code>required string token = 5;</code>
         * @return The bytes for token.
         */
        com.google.protobuf.ByteString
        getTokenBytes();

        /**
         * <code>required int64 timestamp = 6;</code>
         * @return Whether the timestamp field is set.
         */
        boolean hasTimestamp();
        /**
         * <code>required int64 timestamp = 6;</code>
         * @return The timestamp.
         */
        long getTimestamp();
    }
    /**
     * Protobuf type {@code im.AuthenticateResponse}
     */
    public static final class AuthenticateResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:im.AuthenticateResponse)
            AuthenticateResponseOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use AuthenticateResponse.newBuilder() to construct.
        private AuthenticateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private AuthenticateResponse() {
            errorMessage_ = "";
            uid_ = "";
            token_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new AuthenticateResponse();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private AuthenticateResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            bitField0_ |= 0x00000001;
                            status_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            errorCode_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            errorMessage_ = bs;
                            break;
                        }
                        case 34: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000008;
                            uid_ = bs;
                            break;
                        }
                        case 42: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000010;
                            token_ = bs;
                            break;
                        }
                        case 48: {
                            bitField0_ |= 0x00000020;
                            timestamp_ = input.readInt64();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.zsxg.im.protocol.AuthenticateResponseProto.internal_static_im_AuthenticateResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.zsxg.im.protocol.AuthenticateResponseProto.internal_static_im_AuthenticateResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse.class, com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse.Builder.class);
        }

        private int bitField0_;
        public static final int STATUS_FIELD_NUMBER = 1;
        private int status_;
        /**
         * <code>required int32 status = 1;</code>
         * @return Whether the status field is set.
         */
        @java.lang.Override
        public boolean hasStatus() {
            return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required int32 status = 1;</code>
         * @return The status.
         */
        @java.lang.Override
        public int getStatus() {
            return status_;
        }

        public static final int ERRORCODE_FIELD_NUMBER = 2;
        private int errorCode_;
        /**
         * <code>required int32 errorCode = 2;</code>
         * @return Whether the errorCode field is set.
         */
        @java.lang.Override
        public boolean hasErrorCode() {
            return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>required int32 errorCode = 2;</code>
         * @return The errorCode.
         */
        @java.lang.Override
        public int getErrorCode() {
            return errorCode_;
        }

        public static final int ERRORMESSAGE_FIELD_NUMBER = 3;
        private volatile java.lang.Object errorMessage_;
        /**
         * <code>required string errorMessage = 3;</code>
         * @return Whether the errorMessage field is set.
         */
        @java.lang.Override
        public boolean hasErrorMessage() {
            return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>required string errorMessage = 3;</code>
         * @return The errorMessage.
         */
        @java.lang.Override
        public java.lang.String getErrorMessage() {
            java.lang.Object ref = errorMessage_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    errorMessage_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string errorMessage = 3;</code>
         * @return The bytes for errorMessage.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getErrorMessageBytes() {
            java.lang.Object ref = errorMessage_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                errorMessage_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int UID_FIELD_NUMBER = 4;
        private volatile java.lang.Object uid_;
        /**
         * <code>required string uid = 4;</code>
         * @return Whether the uid field is set.
         */
        @java.lang.Override
        public boolean hasUid() {
            return ((bitField0_ & 0x00000008) != 0);
        }
        /**
         * <code>required string uid = 4;</code>
         * @return The uid.
         */
        @java.lang.Override
        public java.lang.String getUid() {
            java.lang.Object ref = uid_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    uid_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string uid = 4;</code>
         * @return The bytes for uid.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getUidBytes() {
            java.lang.Object ref = uid_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                uid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TOKEN_FIELD_NUMBER = 5;
        private volatile java.lang.Object token_;
        /**
         * <code>required string token = 5;</code>
         * @return Whether the token field is set.
         */
        @java.lang.Override
        public boolean hasToken() {
            return ((bitField0_ & 0x00000010) != 0);
        }
        /**
         * <code>required string token = 5;</code>
         * @return The token.
         */
        @java.lang.Override
        public java.lang.String getToken() {
            java.lang.Object ref = token_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    token_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string token = 5;</code>
         * @return The bytes for token.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getTokenBytes() {
            java.lang.Object ref = token_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                token_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TIMESTAMP_FIELD_NUMBER = 6;
        private long timestamp_;
        /**
         * <code>required int64 timestamp = 6;</code>
         * @return Whether the timestamp field is set.
         */
        @java.lang.Override
        public boolean hasTimestamp() {
            return ((bitField0_ & 0x00000020) != 0);
        }
        /**
         * <code>required int64 timestamp = 6;</code>
         * @return The timestamp.
         */
        @java.lang.Override
        public long getTimestamp() {
            return timestamp_;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasStatus()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasErrorCode()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasErrorMessage()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasUid()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasToken()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasTimestamp()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeInt32(1, status_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeInt32(2, errorCode_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorMessage_);
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, uid_);
            }
            if (((bitField0_ & 0x00000010) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, token_);
            }
            if (((bitField0_ & 0x00000020) != 0)) {
                output.writeInt64(6, timestamp_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, status_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, errorCode_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorMessage_);
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, uid_);
            }
            if (((bitField0_ & 0x00000010) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, token_);
            }
            if (((bitField0_ & 0x00000020) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(6, timestamp_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse)) {
                return super.equals(obj);
            }
            com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse other = (com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse) obj;

            if (hasStatus() != other.hasStatus()) return false;
            if (hasStatus()) {
                if (getStatus()
                        != other.getStatus()) return false;
            }
            if (hasErrorCode() != other.hasErrorCode()) return false;
            if (hasErrorCode()) {
                if (getErrorCode()
                        != other.getErrorCode()) return false;
            }
            if (hasErrorMessage() != other.hasErrorMessage()) return false;
            if (hasErrorMessage()) {
                if (!getErrorMessage()
                        .equals(other.getErrorMessage())) return false;
            }
            if (hasUid() != other.hasUid()) return false;
            if (hasUid()) {
                if (!getUid()
                        .equals(other.getUid())) return false;
            }
            if (hasToken() != other.hasToken()) return false;
            if (hasToken()) {
                if (!getToken()
                        .equals(other.getToken())) return false;
            }
            if (hasTimestamp() != other.hasTimestamp()) return false;
            if (hasTimestamp()) {
                if (getTimestamp()
                        != other.getTimestamp()) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasStatus()) {
                hash = (37 * hash) + STATUS_FIELD_NUMBER;
                hash = (53 * hash) + getStatus();
            }
            if (hasErrorCode()) {
                hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
                hash = (53 * hash) + getErrorCode();
            }
            if (hasErrorMessage()) {
                hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
                hash = (53 * hash) + getErrorMessage().hashCode();
            }
            if (hasUid()) {
                hash = (37 * hash) + UID_FIELD_NUMBER;
                hash = (53 * hash) + getUid().hashCode();
            }
            if (hasToken()) {
                hash = (37 * hash) + TOKEN_FIELD_NUMBER;
                hash = (53 * hash) + getToken().hashCode();
            }
            if (hasTimestamp()) {
                hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getTimestamp());
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code im.AuthenticateResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:im.AuthenticateResponse)
                com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.zsxg.im.protocol.AuthenticateResponseProto.internal_static_im_AuthenticateResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.zsxg.im.protocol.AuthenticateResponseProto.internal_static_im_AuthenticateResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse.class, com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse.Builder.class);
            }

            // Construct using com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                status_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                errorCode_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                errorMessage_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                uid_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                token_ = "";
                bitField0_ = (bitField0_ & ~0x00000010);
                timestamp_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000020);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.zsxg.im.protocol.AuthenticateResponseProto.internal_static_im_AuthenticateResponse_descriptor;
            }

            @java.lang.Override
            public com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse getDefaultInstanceForType() {
                return com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse.getDefaultInstance();
            }

            @java.lang.Override
            public com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse build() {
                com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse buildPartial() {
                com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse result = new com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.status_ = status_;
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.errorCode_ = errorCode_;
                    to_bitField0_ |= 0x00000002;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.errorMessage_ = errorMessage_;
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.uid_ = uid_;
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.token_ = token_;
                if (((from_bitField0_ & 0x00000020) != 0)) {
                    result.timestamp_ = timestamp_;
                    to_bitField0_ |= 0x00000020;
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse) {
                    return mergeFrom((com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse other) {
                if (other == com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse.getDefaultInstance()) return this;
                if (other.hasStatus()) {
                    setStatus(other.getStatus());
                }
                if (other.hasErrorCode()) {
                    setErrorCode(other.getErrorCode());
                }
                if (other.hasErrorMessage()) {
                    bitField0_ |= 0x00000004;
                    errorMessage_ = other.errorMessage_;
                    onChanged();
                }
                if (other.hasUid()) {
                    bitField0_ |= 0x00000008;
                    uid_ = other.uid_;
                    onChanged();
                }
                if (other.hasToken()) {
                    bitField0_ |= 0x00000010;
                    token_ = other.token_;
                    onChanged();
                }
                if (other.hasTimestamp()) {
                    setTimestamp(other.getTimestamp());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasStatus()) {
                    return false;
                }
                if (!hasErrorCode()) {
                    return false;
                }
                if (!hasErrorMessage()) {
                    return false;
                }
                if (!hasUid()) {
                    return false;
                }
                if (!hasToken()) {
                    return false;
                }
                if (!hasTimestamp()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private int status_ ;
            /**
             * <code>required int32 status = 1;</code>
             * @return Whether the status field is set.
             */
            @java.lang.Override
            public boolean hasStatus() {
                return ((bitField0_ & 0x00000001) != 0);
            }
            /**
             * <code>required int32 status = 1;</code>
             * @return The status.
             */
            @java.lang.Override
            public int getStatus() {
                return status_;
            }
            /**
             * <code>required int32 status = 1;</code>
             * @param value The status to set.
             * @return This builder for chaining.
             */
            public Builder setStatus(int value) {
                bitField0_ |= 0x00000001;
                status_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required int32 status = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearStatus() {
                bitField0_ = (bitField0_ & ~0x00000001);
                status_ = 0;
                onChanged();
                return this;
            }

            private int errorCode_ ;
            /**
             * <code>required int32 errorCode = 2;</code>
             * @return Whether the errorCode field is set.
             */
            @java.lang.Override
            public boolean hasErrorCode() {
                return ((bitField0_ & 0x00000002) != 0);
            }
            /**
             * <code>required int32 errorCode = 2;</code>
             * @return The errorCode.
             */
            @java.lang.Override
            public int getErrorCode() {
                return errorCode_;
            }
            /**
             * <code>required int32 errorCode = 2;</code>
             * @param value The errorCode to set.
             * @return This builder for chaining.
             */
            public Builder setErrorCode(int value) {
                bitField0_ |= 0x00000002;
                errorCode_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required int32 errorCode = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearErrorCode() {
                bitField0_ = (bitField0_ & ~0x00000002);
                errorCode_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object errorMessage_ = "";
            /**
             * <code>required string errorMessage = 3;</code>
             * @return Whether the errorMessage field is set.
             */
            public boolean hasErrorMessage() {
                return ((bitField0_ & 0x00000004) != 0);
            }
            /**
             * <code>required string errorMessage = 3;</code>
             * @return The errorMessage.
             */
            public java.lang.String getErrorMessage() {
                java.lang.Object ref = errorMessage_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        errorMessage_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string errorMessage = 3;</code>
             * @return The bytes for errorMessage.
             */
            public com.google.protobuf.ByteString
            getErrorMessageBytes() {
                java.lang.Object ref = errorMessage_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    errorMessage_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string errorMessage = 3;</code>
             * @param value The errorMessage to set.
             * @return This builder for chaining.
             */
            public Builder setErrorMessage(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                errorMessage_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string errorMessage = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearErrorMessage() {
                bitField0_ = (bitField0_ & ~0x00000004);
                errorMessage_ = getDefaultInstance().getErrorMessage();
                onChanged();
                return this;
            }
            /**
             * <code>required string errorMessage = 3;</code>
             * @param value The bytes for errorMessage to set.
             * @return This builder for chaining.
             */
            public Builder setErrorMessageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                errorMessage_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object uid_ = "";
            /**
             * <code>required string uid = 4;</code>
             * @return Whether the uid field is set.
             */
            public boolean hasUid() {
                return ((bitField0_ & 0x00000008) != 0);
            }
            /**
             * <code>required string uid = 4;</code>
             * @return The uid.
             */
            public java.lang.String getUid() {
                java.lang.Object ref = uid_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        uid_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string uid = 4;</code>
             * @return The bytes for uid.
             */
            public com.google.protobuf.ByteString
            getUidBytes() {
                java.lang.Object ref = uid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    uid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string uid = 4;</code>
             * @param value The uid to set.
             * @return This builder for chaining.
             */
            public Builder setUid(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                uid_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string uid = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearUid() {
                bitField0_ = (bitField0_ & ~0x00000008);
                uid_ = getDefaultInstance().getUid();
                onChanged();
                return this;
            }
            /**
             * <code>required string uid = 4;</code>
             * @param value The bytes for uid to set.
             * @return This builder for chaining.
             */
            public Builder setUidBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                uid_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object token_ = "";
            /**
             * <code>required string token = 5;</code>
             * @return Whether the token field is set.
             */
            public boolean hasToken() {
                return ((bitField0_ & 0x00000010) != 0);
            }
            /**
             * <code>required string token = 5;</code>
             * @return The token.
             */
            public java.lang.String getToken() {
                java.lang.Object ref = token_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        token_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string token = 5;</code>
             * @return The bytes for token.
             */
            public com.google.protobuf.ByteString
            getTokenBytes() {
                java.lang.Object ref = token_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    token_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string token = 5;</code>
             * @param value The token to set.
             * @return This builder for chaining.
             */
            public Builder setToken(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                token_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string token = 5;</code>
             * @return This builder for chaining.
             */
            public Builder clearToken() {
                bitField0_ = (bitField0_ & ~0x00000010);
                token_ = getDefaultInstance().getToken();
                onChanged();
                return this;
            }
            /**
             * <code>required string token = 5;</code>
             * @param value The bytes for token to set.
             * @return This builder for chaining.
             */
            public Builder setTokenBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                token_ = value;
                onChanged();
                return this;
            }

            private long timestamp_ ;
            /**
             * <code>required int64 timestamp = 6;</code>
             * @return Whether the timestamp field is set.
             */
            @java.lang.Override
            public boolean hasTimestamp() {
                return ((bitField0_ & 0x00000020) != 0);
            }
            /**
             * <code>required int64 timestamp = 6;</code>
             * @return The timestamp.
             */
            @java.lang.Override
            public long getTimestamp() {
                return timestamp_;
            }
            /**
             * <code>required int64 timestamp = 6;</code>
             * @param value The timestamp to set.
             * @return This builder for chaining.
             */
            public Builder setTimestamp(long value) {
                bitField0_ |= 0x00000020;
                timestamp_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required int64 timestamp = 6;</code>
             * @return This builder for chaining.
             */
            public Builder clearTimestamp() {
                bitField0_ = (bitField0_ & ~0x00000020);
                timestamp_ = 0L;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:im.AuthenticateResponse)
        }

        // @@protoc_insertion_point(class_scope:im.AuthenticateResponse)
        private static final com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse();
        }

        public static com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated public static final com.google.protobuf.Parser<AuthenticateResponse>
                PARSER = new com.google.protobuf.AbstractParser<AuthenticateResponse>() {
            @java.lang.Override
            public AuthenticateResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new AuthenticateResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<AuthenticateResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<AuthenticateResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.zsxg.im.protocol.AuthenticateResponseProto.AuthenticateResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_im_AuthenticateResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_im_AuthenticateResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\032AuthenticateResponse.ptoto\022\002im\"~\n\024Auth" +
                        "enticateResponse\022\016\n\006status\030\001 \002(\005\022\021\n\terro" +
                        "rCode\030\002 \002(\005\022\024\n\014errorMessage\030\003 \002(\t\022\013\n\003uid" +
                        "\030\004 \002(\t\022\r\n\005token\030\005 \002(\t\022\021\n\ttimestamp\030\006 \002(\003" +
                        "B1\n\024com.zsxg.im.protocolB\031AuthenticateRe" +
                        "sponseProto"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_im_AuthenticateResponse_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_im_AuthenticateResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_im_AuthenticateResponse_descriptor,
                new java.lang.String[] { "Status", "ErrorCode", "ErrorMessage", "Uid", "Token", "Timestamp", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
